name: Deploy Hexo Blog
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull_request]
jobs:
    deploy_hexo_blog:
      name: Deploy Hexo Blog Job
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v4
          with:
            submodules: 'true'
        - name: Get Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '22'
        - name: Get Hexo
          run: |
            npm install hexo -g
            npm install
            hexo --version
        - name: Set Git Config & Env
          env:
            BLOG_ACCESS_TOKEN: ${{ secrets.BLOG_ACCESS_TOKEN }}
          run: |
            git config --global user.email "sakura286@outlook.com"
            git config --global user.name "Sakura286"
            sed -i "s/BLOG_ACCESS_TOKEN/$BLOG_ACCESS_TOKEN/g" ./_config.yml
        - name: Generate & Deploy
          run: |
            hexo clean
            hexo generate
            hexo deploy
        - run: echo 'Successfully Deployed.'

